// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4UWuoUxBjJSz5QMN4ogHwp
// Component: 9PguJREveg
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 4UWuoUxBjJSz5QMN4ogHwp/projectcss
import sty from "./PlasmicCc.module.css"; // plasmic-import: 9PguJREveg/css

export type PlasmicCc__VariantMembers = {};
export type PlasmicCc__VariantsArgs = {};
type VariantPropType = keyof PlasmicCc__VariantsArgs;
export const PlasmicCc__VariantProps = new Array<VariantPropType>();

export type PlasmicCc__ArgsType = {};
type ArgPropType = keyof PlasmicCc__ArgsType;
export const PlasmicCc__ArgProps = new Array<ArgPropType>();

export type PlasmicCc__OverridesType = {
  frame6?: p.Flex<"div">;
  text?: p.Flex<"div">;
  rectangle2?: p.Flex<"textarea">;
};

export interface DefaultCcProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicCc__RenderFunc(props: {
  variants: PlasmicCc__VariantsArgs;
  args: PlasmicCc__ArgsType;
  overrides: PlasmicCc__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"frame6"}
      data-plasmic-override={overrides.frame6}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.frame6
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Password"}
      </div>

      <textarea
        data-plasmic-name={"rectangle2"}
        data-plasmic-override={overrides.rectangle2}
        className={classNames(
          projectcss.all,
          projectcss.textarea,
          sty.rectangle2
        )}
        disabled={false}
        placeholder={"Wachtwoord" as const}
        ref={ref => {
          $refs["rectangle2"] = ref;
        }}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame6: ["frame6", "text", "rectangle2"],
  text: ["text"],
  rectangle2: ["rectangle2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame6: "div";
  text: "div";
  rectangle2: "textarea";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCc__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCc__VariantsArgs;
    args?: PlasmicCc__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCc__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCc__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCc__ArgProps,
          internalVariantPropNames: PlasmicCc__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCc__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame6") {
    func.displayName = "PlasmicCc";
  } else {
    func.displayName = `PlasmicCc.${nodeName}`;
  }
  return func;
}

export const PlasmicCc = Object.assign(
  // Top-level PlasmicCc renders the root element
  makeNodeComponent("frame6"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    rectangle2: makeNodeComponent("rectangle2"),

    // Metadata about props expected for PlasmicCc
    internalVariantProps: PlasmicCc__VariantProps,
    internalArgProps: PlasmicCc__ArgProps
  }
);

export default PlasmicCc;
/* prettier-ignore-end */
