// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4UWuoUxBjJSz5QMN4ogHwp
// Component: YhnFTIPHVr
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 4UWuoUxBjJSz5QMN4ogHwp/projectcss
import sty from "./PlasmicComponent.module.css"; // plasmic-import: YhnFTIPHVr/css

export type PlasmicComponent__VariantMembers = {};
export type PlasmicComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicComponent__VariantsArgs;
export const PlasmicComponent__VariantProps = new Array<VariantPropType>();

export type PlasmicComponent__ArgsType = {};
type ArgPropType = keyof PlasmicComponent__ArgsType;
export const PlasmicComponent__ArgProps = new Array<ArgPropType>();

export type PlasmicComponent__OverridesType = {
  frame7?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  frame3?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultComponentProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicComponent__RenderFunc(props: {
  variants: PlasmicComponent__VariantsArgs;
  args: PlasmicComponent__ArgsType;
  overrides: PlasmicComponent__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"frame7"}
      data-plasmic-override={overrides.frame7}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.frame7
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"292px" as const}
        displayMaxHeight={"none" as const}
        displayMaxWidth={"100%" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={"488px" as const}
        loading={"lazy" as const}
        src={{
          src: "/plasmic/blank_project/images/undrawLoginRe4Vu21.bin",
          fullWidth: 488,
          fullHeight: 292,
          aspectRatio: 1.671233
        }}
      />

      <p.Stack
        as={"div"}
        data-plasmic-name={"frame3"}
        data-plasmic-override={overrides.frame3}
        hasGap={true}
        className={classNames(projectcss.all, sty.frame3)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"open the door"}
        </div>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame7: ["frame7", "img", "frame3", "text"],
  img: ["img"],
  frame3: ["frame3", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame7: "div";
  img: typeof p.PlasmicImg;
  frame3: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicComponent__VariantsArgs;
    args?: PlasmicComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicComponent__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicComponent__ArgProps,
          internalVariantPropNames: PlasmicComponent__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame7") {
    func.displayName = "PlasmicComponent";
  } else {
    func.displayName = `PlasmicComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicComponent = Object.assign(
  // Top-level PlasmicComponent renders the root element
  makeNodeComponent("frame7"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    frame3: makeNodeComponent("frame3"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicComponent
    internalVariantProps: PlasmicComponent__VariantProps,
    internalArgProps: PlasmicComponent__ArgProps
  }
);

export default PlasmicComponent;
/* prettier-ignore-end */
